/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sipetik;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Chynthia
 */

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    koneksi k = new koneksi();
    String datauser, datapass, a,b,c,d,e;
    BufferedImage img;
    File file;
    
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogin = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        cbPass = new javax.swing.JCheckBox();
        tfPass = new javax.swing.JPasswordField();
        tfUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(589, 479));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogin.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/masuk.png"))); // NOI18N
        btnLogin.setBorderPainted(false);
        btnLogin.setContentAreaFilled(false);
        btnLogin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/masukon.png"))); // NOI18N
        btnLogin.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/masuk.png"))); // NOI18N
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 200, 70));

        btnCancel.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/keluarl.png"))); // NOI18N
        btnCancel.setBorderPainted(false);
        btnCancel.setContentAreaFilled(false);
        btnCancel.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/keluarlon.png"))); // NOI18N
        btnCancel.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/keluarl.png"))); // NOI18N
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 200, 68));

        cbPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPassActionPerformed(evt);
            }
        });
        getContentPane().add(cbPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        tfPass.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        tfPass.setForeground(new java.awt.Color(74, 63, 53));
        getContentPane().add(tfPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 387, 36));

        tfUser.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        tfUser.setForeground(new java.awt.Color(74, 63, 53));
        tfUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUserActionPerformed(evt);
            }
        });
        getContentPane().add(tfUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 387, 40));

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(74, 63, 53));
        jLabel3.setText("Kata Sandi");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(74, 63, 53));
        jLabel2.setText("Nama Pengguna");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(74, 63, 53));
        jLabel7.setText("Tampilkan Kata Sandi");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Login.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 600, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUserActionPerformed

    private void cbPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPassActionPerformed
        if(cbPass.isSelected()){
            tfPass.setEchoChar((char)0);
        }
        else{
            tfPass.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_cbPassActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        tfUser.setText("");
        tfPass.setText("");
        cbPass.setSelected(false);
        int a;
        a=JOptionPane.showConfirmDialog(null, "Anda yakin ingin keluar?", "Info", JOptionPane.YES_NO_OPTION);
        if(a==JOptionPane.YES_OPTION){
            System.exit(a);
        }
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        if(tfUser.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Silahkan isi nama pengguna!");
        }
        else if((tfPass.getText().equals(""))){
                JOptionPane.showMessageDialog(null, "Silahkan isi kata sandi!");
        }
        else{
            try {
                k.query="SELECT username, password, kode_pegawai, nama_pegawai, hak_akses, foto from tbpegawai where username='"+tfUser.getText()+"'and password='"+tfPass.getText()+"'";
                k.getData();
                while(k.rs.next()){
                    a = k.rs.getString("username");
                    b = k.rs.getString("password");
                    c = k.rs.getString("hak_akses");
                    d = k.rs.getString("nama_pegawai");
                    e = k.rs.getString("kode_pegawai");
                    file = new File(k.rs.getString("foto"));
                    img = ImageIO.read(file);
                }
                if(a==null||b==null){
                    JOptionPane.showMessageDialog(null, "Nama pengguna atau kata sandi salah!");
                    tfUser.setText("");
                    tfPass.setText("");
                }
                if(c.equals("admin")){
                    frame.fmenu.setVisible(true);
                    this.setVisible(false);
                    frame.fmenu.btnDataPegawai.setVisible(true);
                    frame.fmenu.btnPemasok.setVisible(true);
                    frame.fmenu.btnBatik.setVisible(true);
                    frame.fmenu.btnTransaksi.setVisible(true);
                    frame.fmenu.lblNama.setText(d);
                    frame.transaksi.tfKodeKasir.setText(e);
                    frame.transaksi.tfNamaKasir.setText(d);
                    frame.fmenu.lFoto.setIcon(new ImageIcon(img.getScaledInstance(frame.fmenu.lFoto.getWidth(),frame.fmenu.lFoto.getHeight(), Image.SCALE_SMOOTH)));
                }
                else if(c.equals("operator")){
                    frame.fmenu.setVisible(true);
                    this.setVisible(false);
                    frame.fmenu.btnDataPegawai.setVisible(false);
                    frame.fmenu.btnPemasok.setVisible(true);
                    frame.fmenu.btnBatik.setVisible(true);
                    frame.fmenu.btnTransaksi.setVisible(true);
                    frame.fmenu.lblNama.setText(d);
                    frame.transaksi.tfKodeKasir.setText(e);
                    frame.transaksi.tfNamaKasir.setText(d);
                    frame.fmenu.lFoto.setIcon(new ImageIcon(img.getScaledInstance(frame.fmenu.lFoto.getWidth(),frame.fmenu.lFoto.getHeight(), Image.SCALE_SMOOTH)));
                }
                else if(c.equals("kasir")){
                    frame.transaksi.tfNamaKasir.setText(d);
                    frame.transaksi.tfKodeKasir.setText(e);
                    frame.fmenu.setVisible(true);
                    this.setVisible(false);
                    frame.fmenu.btnDataPegawai.setVisible(false);
                    frame.fmenu.btnPemasok.setVisible(false);
                    frame.fmenu.btnBatik.setVisible(false);
                    frame.fmenu.btnTransaksi.setVisible(true);
                    frame.fmenu.lblNama.setText(d);
                    frame.transaksi.tfKodeKasir.setText(e);
                    frame.transaksi.tfNamaKasir.setText(d);
                    frame.fmenu.lFoto.setIcon(new ImageIcon(img.getScaledInstance(frame.fmenu.lFoto.getWidth(),frame.fmenu.lFoto.getHeight(), Image.SCALE_SMOOTH)));
                }

            }catch(SQLException ss){
                System.out.println("Error: "+ss);
            } catch (IOException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox cbPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField tfPass;
    private javax.swing.JTextField tfUser;
    // End of variables declaration//GEN-END:variables
}
