/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sipetik;

import java.beans.PropertyVetoException;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Chynthia
 */
//INHERITANCE
public class Masuk extends javax.swing.JFrame {

    /**
     * Creates new form Masuk
     */
    public Masuk() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lFoto = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        btnDataPegawai = new javax.swing.JButton();
        btnPemasok = new javax.swing.JButton();
        btnTransaksi = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnBatik = new javax.swing.JButton();
        panelisi = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(74, 63, 53));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Header.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 120));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lFoto.setBackground(new java.awt.Color(255, 255, 255));
        lFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel1.add(lFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 158, 210));

        lblNama.setBackground(new java.awt.Color(255, 255, 255));
        lblNama.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblNama.setForeground(new java.awt.Color(255, 255, 255));
        lblNama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNama.setText("null");
        jPanel1.add(lblNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 351, 150, 30));

        btnDataPegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pegawai.png"))); // NOI18N
        btnDataPegawai.setBorderPainted(false);
        btnDataPegawai.setContentAreaFilled(false);
        btnDataPegawai.setFocusPainted(false);
        btnDataPegawai.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pegawaion.png"))); // NOI18N
        btnDataPegawai.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pegawai.png"))); // NOI18N
        btnDataPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDataPegawaiMouseClicked(evt);
            }
        });
        jPanel1.add(btnDataPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        btnPemasok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pemasok.png"))); // NOI18N
        btnPemasok.setBorderPainted(false);
        btnPemasok.setContentAreaFilled(false);
        btnPemasok.setFocusPainted(false);
        btnPemasok.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pemasokon.png"))); // NOI18N
        btnPemasok.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pemasok.png"))); // NOI18N
        btnPemasok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPemasokMouseClicked(evt);
            }
        });
        btnPemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPemasokActionPerformed(evt);
            }
        });
        jPanel1.add(btnPemasok, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, -1));

        btnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/transaksi.png"))); // NOI18N
        btnTransaksi.setBorderPainted(false);
        btnTransaksi.setContentAreaFilled(false);
        btnTransaksi.setFocusPainted(false);
        btnTransaksi.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/transaksion.png"))); // NOI18N
        btnTransaksi.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/transaksi.png"))); // NOI18N
        btnTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseClicked(evt);
            }
        });
        jPanel1.add(btnTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, -1, -1));

        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/keluar.png"))); // NOI18N
        btnKeluar.setBorderPainted(false);
        btnKeluar.setContentAreaFilled(false);
        btnKeluar.setFocusPainted(false);
        btnKeluar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/keluaron.png"))); // NOI18N
        btnKeluar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/keluar.png"))); // NOI18N
        btnKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKeluarMouseClicked(evt);
            }
        });
        jPanel1.add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 670, -1, -1));

        btnBatik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/batik.png"))); // NOI18N
        btnBatik.setBorderPainted(false);
        btnBatik.setContentAreaFilled(false);
        btnBatik.setFocusPainted(false);
        btnBatik.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/batikon.png"))); // NOI18N
        btnBatik.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/batik.png"))); // NOI18N
        btnBatik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBatikMouseClicked(evt);
            }
        });
        jPanel1.add(btnBatik, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, -1, 70));

        panelisi.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelisiLayout = new javax.swing.GroupLayout(panelisi);
        panelisi.setLayout(panelisiLayout);
        panelisiLayout.setHorizontalGroup(
            panelisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        panelisiLayout.setVerticalGroup(
            panelisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        jPanel1.add(panelisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 1030, 620));

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatikMouseClicked
        try{
            //show frame pegawai

            //remove all component in panelisi
            panelisi.removeAll();

            //menampilkan frame pegawai
            frame.batik.setVisible(true);

            //add panel pegawai ke panelisi
            panelisi.add(frame.batik);

            //set ukuran frame pegawai sesuai ukuran panel isi
            frame.batik.setMaximum(true);

            //menghilangkan border frame pegawai dengan basic frame
            //dan get semua component yang ada dalam frame pegawai
            frame.batik.setBorder(null);
            ((BasicInternalFrameUI)frame.batik.getUI()).setNorthPane(null);
            panelisi.repaint();
        }
        catch(PropertyVetoException e){
            System.out.println("Error" +e);
        }
    }//GEN-LAST:event_btnBatikMouseClicked

    private void btnKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKeluarMouseClicked
        int s= JOptionPane.showConfirmDialog(null, "Apakah anda ingin keluar?", "KELUAR", JOptionPane.YES_NO_OPTION);
        if(s==0){
            new Login().setVisible(true);
            this.hide();
        }
    }//GEN-LAST:event_btnKeluarMouseClicked

    private void btnTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseClicked
        try{
            //show frame pegawai

            //remove all component in panelisi
            panelisi.removeAll();

            //menampilkan frame pegawai
            frame.transaksi.setVisible(true);

            //add panel pegawai ke panelisi
            panelisi.add(frame.transaksi);

            //set ukuran frame pegawai sesuai ukuran panel isi
            frame.transaksi.setMaximum(true);

            //menghilangkan border frame pegawai dengan basic frame
            //dan get semua component yang ada dalam frame pegawai
            frame.transaksi.setBorder(null);
            ((BasicInternalFrameUI)frame.transaksi.getUI()).setNorthPane(null);
            panelisi.repaint();
        }
        catch(PropertyVetoException e){
            System.out.println("Error" +e);
        }
    }//GEN-LAST:event_btnTransaksiMouseClicked

    private void btnPemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPemasokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPemasokActionPerformed

    private void btnPemasokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPemasokMouseClicked
        try{
            //show frame pegawai

            //remove all component in panelisi
            panelisi.removeAll();

            //menampilkan frame pegawai
            frame.pemasok.setVisible(true);

            //add panel pegawai ke panelisi
            panelisi.add(frame.pemasok);

            //set ukuran frame pegawai sesuai ukuran panel isi
            frame.pemasok.setMaximum(true);

            //menghilangkan border frame pegawai dengan basic frame
            //dan get semua component yang ada dalam frame pegawai
            frame.pemasok.setBorder(null);
            ((BasicInternalFrameUI)frame.pemasok.getUI()).setNorthPane(null);
            panelisi.repaint();
        }
        catch(PropertyVetoException e){
            System.out.println("Error" +e);
        }
    }//GEN-LAST:event_btnPemasokMouseClicked

    private void btnDataPegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataPegawaiMouseClicked
        try{
            //show frame pegawai

            //remove all component in panelisi
            panelisi.removeAll();

            //menampilkan frame pegawai
            frame.pegawai.setVisible(true);

            //add panel pegawai ke panelisi
            panelisi.add(frame.pegawai);

            //set ukuran frame pegawai sesuai ukuran panel isi
            frame.pegawai.setMaximum(true);

            //menghilangkan border frame pegawai dengan basic frame
            //dan get semua component yang ada dalam frame pegawai
            frame.pegawai.setBorder(null);
            ((BasicInternalFrameUI)frame.pegawai.getUI()).setNorthPane(null);
            panelisi.repaint();
        }
        catch(PropertyVetoException e){
            System.out.println("Error" +e);
        }
    }//GEN-LAST:event_btnDataPegawaiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Masuk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBatik;
    public javax.swing.JButton btnDataPegawai;
    public javax.swing.JButton btnKeluar;
    public javax.swing.JButton btnPemasok;
    public javax.swing.JButton btnTransaksi;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel lFoto;
    public javax.swing.JLabel lblNama;
    private javax.swing.JPanel panelisi;
    // End of variables declaration//GEN-END:variables
}
